server:
  port: 8080
spring:
  springdoc:
    swagger-ui:
      use-root-path: true
      path: /api-docs
      disable-swagger-default-url: /v2/api-docs
  jpa:
    show-sql: true
    open-in-view: false
  properties:
    hibernate.jdbc.time_zone: UTC
    hibernate.id.new_generator_mappings: true
    hibernate.cache.use_second_level_cache: false
    hibernate.cache.use_query_cache: false
    hibernate.generate_statistics: true
    hibernate.jdbc.lob.non_contextual_creation: true
    # modify batch size as necessary
    hibernate.jdbc.batch_size: 50
    hibernate.order_inserts: true
    hibernate.order_updates: true
    hibernate.query.fail_on_pagination_over_collection_fetch: true
    hibernate.query.in_clause_parameter_padding: true
    hibernate.format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    liquibase:
      enabled: true
    datasource:
      url: jdbc:postgresql://localhost:5432/interior?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&reWriteBatchedInserts=true
      username: postgres
      password: 123
